/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package relayrunners;

import java.util.ArrayList;

/**
 *
 * @author pazzagli.angelica
 */
public class GameForm extends javax.swing.JFrame implements Observer{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameForm.class.getName());
    private ArrayList<Corridore> corridori;
    private GameManager manager;
    /**
     * Creates new form GameForm
     */
    public GameForm() {
        initComponents();
        btnSospendi.setEnabled(false);
        btnRiprendi.setEnabled(false);
        btnFerma.setEnabled(false);
    }
    
    public void setCorridori(ArrayList<Corridore> corridori) {
        this.corridori = corridori;
        lblInfo1.setText(corridori.get(0).getNome());
        lblInfo2.setText(corridori.get(1).getNome());
        lblInfo3.setText(corridori.get(2).getNome());
        lblInfo4.setText(corridori.get(3).getNome());
    }

    public void setManager(GameManager manager) {
        this.manager = manager;
    }
    
    @Override
    public void update(int numeroCorridore, int valore) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            switch (numeroCorridore) {
                case 1 -> {bar1.setValue(valore); lblInfo1.setText(corridori.get(0).getNome() + " - " + valore + "%");}
                case 2 -> {bar2.setValue(valore); lblInfo2.setText(corridori.get(1).getNome() + " - " + valore + "%");}
                case 3 -> {bar3.setValue(valore); lblInfo3.setText(corridori.get(2).getNome() + " - " + valore + "%");}
                case 4 -> {bar4.setValue(valore); lblInfo4.setText(corridori.get(3).getNome() + " - " + valore + "%");}
            }
        });
    }
    
    private void resetProgressBars() {
        bar1.setValue(0);
        bar2.setValue(0);
        bar3.setValue(0);
        bar4.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar2 = new javax.swing.JProgressBar();
        bar3 = new javax.swing.JProgressBar();
        bar4 = new javax.swing.JProgressBar();
        bar1 = new javax.swing.JProgressBar();
        lblInfo4 = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        cmbVelocità = new javax.swing.JComboBox<>();
        btnAvvia = new javax.swing.JButton();
        btnSospendi = new javax.swing.JButton();
        btnRiprendi = new javax.swing.JButton();
        btnFerma = new javax.swing.JButton();
        lblTitolo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 204));

        bar2.setBackground(new java.awt.Color(255, 153, 255));
        bar2.setForeground(new java.awt.Color(255, 255, 255));

        bar3.setBackground(new java.awt.Color(255, 153, 255));
        bar3.setForeground(new java.awt.Color(255, 255, 255));

        bar4.setBackground(new java.awt.Color(255, 153, 255));
        bar4.setForeground(new java.awt.Color(255, 255, 255));

        bar1.setBackground(new java.awt.Color(255, 153, 255));
        bar1.setForeground(new java.awt.Color(255, 255, 255));

        lblInfo4.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblInfo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo4.setText("RUNNER 4");

        lblInfo3.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblInfo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo3.setText("RUNNER 3");

        lblInfo2.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo2.setText("RUNNER 2");

        lblInfo1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo1.setText("RUNNER 1");

        cmbVelocità.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        cmbVelocità.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slow", "Regular", "Fast" }));

        btnAvvia.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnAvvia.setText("AVVIA");
        btnAvvia.addActionListener(this::btnAvviaActionPerformed);

        btnSospendi.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnSospendi.setText("SOSPENDI");
        btnSospendi.addActionListener(this::btnSospendiActionPerformed);

        btnRiprendi.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnRiprendi.setText("RIPRENDI");
        btnRiprendi.addActionListener(this::btnRiprendiActionPerformed);

        btnFerma.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnFerma.setText("FERMA");
        btnFerma.addActionListener(this::btnFermaActionPerformed);

        lblTitolo.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("STAFFETTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bar4, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblInfo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInfo3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bar2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(cmbVelocità, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSospendi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRiprendi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFerma, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bar1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVelocità, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvvia)
                    .addComponent(btnSospendi)
                    .addComponent(btnRiprendi)
                    .addComponent(btnFerma))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        String scelta = (String) cmbVelocità.getSelectedItem();
        manager.setVelocità(scelta);
        manager.startRace();
        btnAvvia.setEnabled(false);
        btnSospendi.setEnabled(true);
        btnFerma.setEnabled(true);
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnSospendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSospendiActionPerformed
        manager.stop();
        btnSospendi.setEnabled(false);
        btnRiprendi.setEnabled(true);
        btnFerma.setEnabled(false);
    }//GEN-LAST:event_btnSospendiActionPerformed

    private void btnRiprendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiprendiActionPerformed
        manager.riprendi();
        btnRiprendi.setEnabled(false);
        btnSospendi.setEnabled(true);
        btnFerma.setEnabled(true);
    }//GEN-LAST:event_btnRiprendiActionPerformed

    private void btnFermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermaActionPerformed
        manager.stopCorsa();
        resetProgressBars();
        manager.resetCorsa();
        manager.attaccaObserver(this);
        btnFerma.setEnabled(false);
        btnSospendi.setEnabled(false);
        btnAvvia.setEnabled(true);
        lblInfo1.setText(corridori.get(0).getNome());
        lblInfo2.setText(corridori.get(1).getNome());
        lblInfo3.setText(corridori.get(2).getNome());
        lblInfo4.setText(corridori.get(3).getNome());
    }//GEN-LAST:event_btnFermaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar1;
    private javax.swing.JProgressBar bar2;
    private javax.swing.JProgressBar bar3;
    private javax.swing.JProgressBar bar4;
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnFerma;
    private javax.swing.JButton btnRiprendi;
    private javax.swing.JButton btnSospendi;
    private javax.swing.JComboBox<String> cmbVelocità;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblInfo4;
    private javax.swing.JLabel lblTitolo;
    // End of variables declaration//GEN-END:variables
}
